name: Deploy to DreamHost via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload files to DreamHost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Deploy to DreamHost
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /rnd.oddly.co/